name: DataUpdate

on:
  watch:
    types: [started]
  schedule:
    - cron: "45 * * * *"
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure Origin
      uses: Boostport/setup-cloudflare-warp@v1
      with: 
        organization: ${{ secrets.CLOUDFLARE_ORGANIZATION }}
        auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
        auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install selenium requests undetected-chromedriver

    - name: Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 135
        install-chromedriver: true
    
    - name: Build
      run: |
        cp ${{ github.workspace }}/run/data.py ${{ github.workspace }}/updater.py
        echo "${{ secrets.DTAPI }}" > api.txt
        sed -i '15 r api.txt' ${{ github.workspace }}/updater.py
        python ${{ github.workspace }}/updater.py
    
